### ISSUE TITLE
Не закрывается старый лаунчер после обновления

### ISSUE THREAD

**Issue by Linked-su** [GravitLauncher/LauncherRuntime#28]
Версия: v5.1.4-1 stable

После обновления(build) лаунчера не закрывается старый лаунчер

Из логов:
Exception in thread "JavaFX Application Thread" java.lang.NullPointerException
        at com.sun.javafx.tk.quantum.QuantumToolkit.isSupported(QuantumToolkit.java:1196)
        at com.sun.javafx.application.PlatformImpl.isSupportedImpl(PlatformImpl.java:809)
        at com.sun.javafx.application.PlatformImpl.isSupported(PlatformImpl.java:482)
        at javafx.application.Platform.isSupported(Platform.java:168)
        at com.sun.javafx.scene.input.PickResultChooser.processOffer(PickResultChooser.java:182)
        at com.sun.javafx.scene.input.PickResultChooser.offer(PickResultChooser.java:143)
        at javafx.scene.Node.impl_intersects(Node.java:4943)
        at javafx.scene.layout.Region.impl_pickNodeLocal(Region.java:2942)
        at javafx.scene.Node.impl_pickNode(Node.java:4912)
        at javafx.scene.layout.Region.impl_pickNodeLocal(Region.java:2936)
        at javafx.scene.Node.impl_pickNode(Node.java:4912)
        at javafx.scene.Scene$MouseHandler.pickNode(Scene.java:3899)
        at javafx.scene.Scene$MouseHandler.access$1600(Scene.java:3485)
        at javafx.scene.Scene.pick(Scene.java:1942)
        at javafx.scene.Scene.access$6700(Scene.java:159)
        at javafx.scene.Scene$MouseHandler.process(Scene.java:3711)
        at javafx.scene.Scene$MouseHandler.access$1500(Scene.java:3485)
        at javafx.scene.Scene.impl_processMouseEvent(Scene.java:1762)
        at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2494)
        at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:394)
        at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:295)
        at java.security.AccessController.doPrivileged(Native Method)
        at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(GlassViewEventHandler.java:432)
        at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:410)
        at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:431)
        at com.sun.glass.ui.View.handleMouseEvent(View.java:555)
        at com.sun.glass.ui.View.notifyMouse(View.java:937)
        at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
        at com.sun.glass.ui.win.WinApplication.lambda$null$4(WinApplication.java:186)
        at java.lang.Thread.run(Unknown Source)

**Comment by gravit0** [comment]
Лог не даёт никакой полезной информации, нет информации об установленных модулях и последовательности действий

**Comment by Linked-su** [comment]
Лаунчсервер скачал тут: https://github.com/GravitLauncher/Launcher/actions/runs/88509484
runtime скачал тут: https://github.com/GravitLauncher/LauncherRuntime/actions/runs/88514705

Из модулей:
- AdditionalHash_module
- AutoReHash_module
- AutoSaveSessions_module
- ServerScriptEngine_module

Из модулей launcher-modules:

- DiscordRPC_lmodule
- JavaRuntime-1.1.0

Последовательность:

Делаем новый build

1. Дожидаемся окончание
2. Запускаем старый лаунчер
3. Он загружает новый
4. Запускается новый лаунчер
5. Старый остается со сценой "update" -> "Проверка обновлений лаунчера"
----
Данная ошибка из лога(1 пост) выдается если навести курсор мышки на старый лаунчер.

**Comment by gravit0** [comment]
DiscordRPC откуда был взят? Повторяется ли проблема без него?

**Comment by gravit0** [comment]
Проверьте так же на этой сборке https://github.com/GravitLauncher/LauncherRuntime/actions/runs/88504975
Захар в обход всех code flow правил закоммитил изменение прямо в master и при слиянии могли возникнуть конфликты. Коммит выше прямо перед слиянием

**Comment by Linked-su** [comment]
> DiscordRPC откуда был взят? Повторяется ли проблема без него?
Ошибка повторяется и без данного модуля


> Проверьте так же на этой сборке https://github.com/GravitLauncher/LauncherRuntime/actions/runs/88504975
> Захар в обход всех code flow правил закоммитил изменение прямо в master и при слиянии могли возникнуть конфликты. Коммит выше прямо перед слиянием

Так же

**Comment by gunirs** [comment]
Та же самая проблема.

Использую 5.1.4 (build #1).
Из модулей: UnsafeCommandPack (без него была та же самая проблема).
Runtime v1.1.0 stable runtime for 5.1.4-stablr (последний на данный момент).

**Comment by gravit0** [comment]
https://github.com/GravitLauncher/LauncherRuntime/commit/2c20fb4078196bd12b0e227096213f70acde3bcc
